import streamlit as st
import pandas as pd
from utils.data_loader import load_customer_data
from utils.sidebar import load_sidebar
from utils.charts import histogram_chart, scatter_chart, bar_chart, donut_chart, horizontal_bar_chart

# Page Config
st.set_page_config(
    page_title="CustomerInsight - Spending Analysis",
    page_icon="💰",
    layout="wide"
)

# Load data and apply filters
df = load_customer_data()
filtered_df = load_sidebar(df, page_name="Spending Analysis")

st.markdown("<h1 style='margin-bottom: 5px;'>Spending Analysis</h1>", unsafe_allow_html=True)
st.markdown("<p style='color: #64748B; font-size: 1rem; margin-bottom: 25px;'>Comprehensive monetary evaluation: income profiles, customer lifetime value, basket sizing, and high-value cohort analysis.</p>", unsafe_allow_html=True)

if filtered_df.empty:
    st.warning("⚠️ No data available for the selected filters. Please adjust the sidebar filters.")
else:
    # Row 1: Income Distribution & Customer Spending Scatter (Income vs Total Spend)
    r1c1, r1c2 = st.columns([1, 1], gap="medium")
    
    with r1c1:
        with st.container(key="spending_chart_1"):
            fig_income = histogram_chart(filtered_df, x="Annual_Income", title="Annual Income Distribution (INR)", nbins=25)
            st.plotly_chart(fig_income, use_container_width=True)
            
    with r1c2:
        with st.container(key="spending_chart_2"):
            fig_inc_spend = scatter_chart(
                filtered_df, 
                x="Annual_Income", 
                y="Total_Spend", 
                color="Membership_Type", 
                title="Annual Income vs. Cumulative Spending"
            )
            st.plotly_chart(fig_inc_spend, use_container_width=True)
            
    st.markdown("<div style='height: 25px;'></div>", unsafe_allow_html=True)
    
    # Row 2: Revenue by Category & Average Basket Size
    r2c1, r2c2 = st.columns([1, 1], gap="medium")
    
    with r2c1:
        with st.container(key="spending_chart_3"):
            rev_cat = filtered_df.groupby("Preferred_Category")["Total_Spend"].sum().reset_index()
            rev_cat = rev_cat.sort_values(by="Total_Spend", ascending=True)
            rev_cat.columns = ["Category", "Total Revenue (₹)"]
            
            fig_rev_cat = horizontal_bar_chart(rev_cat, x="Total Revenue (₹)", y="Category", title="Revenue Generated by Category")
            st.plotly_chart(fig_rev_cat, use_container_width=True)
            
    with r2c2:
        with st.container(key="spending_chart_4"):
            fig_basket = histogram_chart(filtered_df, x="Items_Purchased", title="Customer Basket Size Distribution (Total Items)", nbins=20)
            st.plotly_chart(fig_basket, use_container_width=True)
            
    st.markdown("<div style='height: 25px;'></div>", unsafe_allow_html=True)
    
    # Row 3: Revenue by City & Revenue by Gender
    r3c1, r3c2 = st.columns([3, 2], gap="medium")
    
    with r3c1:
        with st.container(key="spending_chart_5"):
            city_rev = filtered_df.groupby("City")["Total_Spend"].sum().reset_index()
            city_rev = city_rev.sort_values(by="Total_Spend", ascending=False).head(10)
            city_rev.columns = ["City", "Revenue (₹)"]
            
            fig_city_rev = bar_chart(city_rev, x="City", y="Revenue (₹)", title="Top 10 Cities by Revenue Share")
            st.plotly_chart(fig_city_rev, use_container_width=True)
            
    with r3c2:
        with st.container(key="spending_chart_6"):
            gender_rev = filtered_df.groupby("Gender")["Total_Spend"].sum().reset_index()
            gender_rev.columns = ["Gender", "Revenue Share"]
            
            fig_gender_rev = donut_chart(gender_rev, names="Gender", values="Revenue Share", title="Revenue Contribution by Gender")
            st.plotly_chart(fig_gender_rev, use_container_width=True)
            
    st.markdown("<div style='height: 25px;'></div>", unsafe_allow_html=True)
    
    # Row 4: High Value Customers Cohort Analysis
    with st.container(key="spending_hvc_block"):
        st.markdown("### 💎 High-Value Customers (HVC) Cohort")
        st.markdown("Evaluating the top 10% highest spenders within the filtered cohort.")
        
        # Calculate thresholds
        hvc_threshold = filtered_df["Total_Spend"].quantile(0.90)
        hvc_cohort = filtered_df[filtered_df["Total_Spend"] >= hvc_threshold]
        
        hvc_count = len(hvc_cohort)
        hvc_revenue = hvc_cohort["Total_Spend"].sum()
        total_revenue = filtered_df["Total_Spend"].sum()
        hvc_revenue_share = (hvc_revenue / total_revenue) * 100 if total_revenue > 0 else 0
        
        m1, m2, m3 = st.columns(3)
        with m1:
            st.metric(label="HVC Count (Top 10% threshold)", value=f"{hvc_count:,}")
        with m2:
            st.metric(label="HVC Revenue Contribution", value=f"₹{hvc_revenue / 100000:.1f} L" if hvc_revenue < 10000000 else f"₹{hvc_revenue / 10000000:.2f} Cr")
        with m3:
            st.metric(label="Revenue Contribution Share", value=f"{hvc_revenue_share:.1f}%", help="Pareto principle snapshot: top 10% customers generate this percentage of total spend.")
            
        st.markdown("#### Top 10 High-Value Spenders Profile")
        top_10_hvc = hvc_cohort.sort_values(by="Total_Spend", ascending=False).head(10)[
            ["Customer_ID", "Age", "Gender", "City", "Membership_Type", "Total_Spend", "Loyalty_Score"]
        ]
        top_10_hvc.columns = ["Customer ID", "Age", "Gender", "City", "Membership", "Total Spend (₹)", "Loyalty Score"]
        
        st.dataframe(top_10_hvc.style.format({"Total Spend (₹)": "₹{:,.2f}"}), use_container_width=True, hide_index=True)
        
    st.markdown("<div style='height: 25px;'></div>", unsafe_allow_html=True)
    
    # Row 5: Business Insights
    with st.container(key="spending_insights"):
        st.markdown("### 💰 Spending Analysis Insights")
        st.markdown(
            f"""
            - **Income-Spend Relationship:** The scatter chart highlights a strong correlation between annual income and total lifetime spending. 
              **VIP** and **Gold** tier members group tightly at higher annual income brackets and demonstrate higher spending velocity.
            - **Concentration of Spends:** A classic **Pareto distribution** is visible: the top **10%** of spenders (HVC cohort) account for 
              approximately **{hvc_revenue_share:.1f}%** of the total revenue! Ensuring retention of this group is critical.
            - **Category Revenue Drivers:** **Electronics** represents the largest slice of revenue due to a high average order value, 
              while **Apparel** remains a key driver in volume.
            - **Geographic Value:** **{city_rev.iloc[0]['City']}** is the highest revenue-generating city, followed by **{city_rev.iloc[1]['City']}**. 
              Targeted local marketing in these high-performing metro zones offers immediate ROI.
            - **Gender Spending Equality:** The revenue contribution between Genders is highly balanced, mirroring the user distribution 
              and confirming that campaigns should be neutral.
            """,
            unsafe_allow_html=True
        )
        
    st.markdown("<div style='height: 40px;'></div>", unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("<p style='text-align: center; color: #94A3B8; font-size: 0.85rem;'>CustomerInsight Dashboard v1.0.0 | Spending Analysis Module</p>", unsafe_allow_html=True)
